# Generated by Django 4.0.2 on 2022-02-27 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubquestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='answer')),
                ('interrogator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='interrogator')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subquestionbase', verbose_name='question')),
                ('responder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.responder', verbose_name='responder')),
            ],
        ),
    ]
