# Generated by Django 4.0.2 on 2022-02-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestionbase',
            name='q_type',
        ),
        migrations.AddField(
            model_name='subquestionbase',
            name='predefined_answer',
            field=models.TextField(blank=True, null=True, verbose_name='predefined answer'),
        ),
        migrations.AlterField(
            model_name='primaryquestionbase',
            name='question',
            field=models.TextField(verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='subquestionanswer',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='subquestionbase',
            name='question',
            field=models.TextField(verbose_name='question'),
        ),
    ]
