# Generated by Django 4.0.2 on 2022-02-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_subquestionbase_q_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responder',
            name='birth_date',
        ),
    ]
