# Generated by Django 4.0.2 on 2022-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_responder_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='respondrs birth date'),
        ),
    ]
