# Generated by Django 4.0.2 on 2022-02-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_responder_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='interrogator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='interrogator'),
            preserve_default=False,
        ),
    ]
